name: project_2
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  project_1: ^1.0.0

dependency_overrides:
  project_1:
    path: ../project_1
    version: 1.0.0
